DROP INDEX IF EXISTS idx_users_role;
DROP INDEX IF EXISTS idx_users_status;
ALTER TABLE users DROP CONSTRAINT IF EXISTS check_status;
ALTER TABLE users DROP COLUMN IF EXISTS status;
ALTER TABLE users DROP CONSTRAINT IF EXISTS check_role;
ALTER TABLE users DROP COLUMN IF EXISTS role;
